apiVersion: v1
data:
  Caddyfile: |
    0.0.0.0:2015
    root /var/www/html
    log stdout
    errors stdout
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: caddy-ocp101-demo-static
  labels:
    app: ocp101-demo-static
    deploymentconfig: ocp101-demo-static
    app-name: ocp101-demo-static
