apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: ocp101-demo
    name: ocp101-demo
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ocp101-demo:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: web
      git:
        uri: https://github.com/patricksimonian/ocp101-s2i-build-deploy
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:10
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 5c13fQ2IAHJBRMpmvHg8
      type: GitHub
    - generic:
        secret: mlnqCvtzImzBkHmko4Zx
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
